In [3]:
import numpy as np
from numpy import genfromtxt

In [9]:
my_list = [6,9,5,3,"a",7,10,11]
my_array = np.array(my_list)

[ 6.  9.  5.  3.  7. 10. 11.]


In [13]:
my_array

array([ 6.,  9.,  5.,  3.,  7., 10., 11.], dtype=float16)

In [21]:
my_list2 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
my_array2 = np.array(my_list2)
print(my_array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
accounts = genfromtxt("Accounts.csv", delimiter = "," , dtype=str)

In [9]:
accounts

array([[           nan,            nan,            nan, 1.23456789e+13,
        1.23456789e+10,            nan, 1.23400000e+03, 2.03100000e+04],
       [           nan,            nan,            nan, 1.23456779e+09,
        1.23456789e+10,            nan, 2.34500000e+03, 0.00000000e+00],
       [           nan,            nan,            nan, 1.23456789e+13,
        1.23456789e+10,            nan, 1.23400000e+03, 2.03100000e+04],
       [           nan,            nan,            nan, 1.23456789e+13,
        1.23456789e+10,            nan, 1.23400000e+03, 1.93100000e+04],
       [           nan,            nan,            nan, 1.23456789e+13,
        1.23456789e+10,            nan, 1.23400000e+03, 1.93100000e+04]])

In [10]:
header = accounts[0]

In [11]:
header

array([           nan,            nan,            nan, 1.23456789e+13,
       1.23456789e+10,            nan, 1.23400000e+03, 2.03100000e+04])