In [1]:
import numpy as np
from numpy import genfromtxt

In [35]:
student_record= genfromtxt("Students.csv",delimiter=',',dtype=float)
student_record = np.delete(student_record,0,0)
student_record

array([[50., 70., 90., 80., 85.],
       [55., 72., 60., 70., 75.],
       [80., 50., 90., 83., 65.],
       [50., 60., 80., 87., 65.],
       [53., 40., 83., 70., 95.],
       [50., 62., 87., 80., 45.],
       [40., 73., 60., 70., 55.],
       [59., 75., 60., 30., 65.],
       [68., 60., 80., 30., 75.],
       [58., 70., 50., 80., 65.]])

In [34]:
max_marks_perSub = student_record.max(axis=0)
max_marks_perSub

array([nan, nan, nan, nan, nan])

In [20]:
total_marks = np.sum(student_record,axis=1)
total_marks_copy = total_marks.copy()
total_marks

array([375., 332., 368., 342., 341., 324., 298., 289., 313., 323.])

In [21]:
percentage = (total_marks/500)*100
percentage

array([75. , 66.4, 73.6, 68.4, 68.2, 64.8, 59.6, 57.8, 62.6, 64.6])

In [32]:
# A_grade = percentage.where(percentage>80)
# B_grade = percentage.where(percentage>60) & (percentage<80)
# C_grade = percentage.where(percentage>40) & (percentage<60)
# F_grade = percentage.where(percentage<40)

# A_grade
# B_grade
# C_grade
# F_grade
#percentage.where(percentage>80)
A_grade = np.where(percentage>80,'A',percentage)
A_grade = np.where((lpercentage>80,'A',percentage)
A_grade = np.where(percentage>80,'A',percentage)
A_grade = np.where(percentage>80,'A',percentage)

array(['75.0', '66.4', '73.6', '68.4', '68.2', '64.8',
       '59.599999999999994', '57.8', '62.6', '64.60000000000001'],
      dtype='<U32')

In [26]:
ranking = percentage.argsort()[::-1]
full_ranking = ranking + 1
full_ranking

array([ 1,  3,  4,  5,  2,  6, 10,  9,  7,  8])