In [4]:
import numpy as np

In [6]:
array = np.array([[40,50,80,90],[40,55,89,70],[30,60,80,60],[20,90,70,50],[30,70,40,80]])
array

array([[40, 50, 80, 90],
       [40, 55, 89, 70],
       [30, 60, 80, 60],
       [20, 90, 70, 50],
       [30, 70, 40, 80]])

In [8]:
array.sum(axis=1)

array([260, 254, 230, 230, 220])

In [11]:
perc_array = array.sum(axis=1).copy()
(perc_array / 400 ) * 100

array([65. , 63.5, 57.5, 57.5, 55. ])

In [15]:
sort_arr = np.argsort((perc_array / 400 ) * 100)
sort_arr

array([4, 3, 2, 1, 0])