In [1]:
import numpy as np

<h1>Creating Array From List</h1>

In [3]:
array_1D = np.array([1,2,3,4,5,6,7])
print("1D Array: ",array_1D)
array_2D = np.array([[1,2,3],[4,5,6]])
print("2D Array: ", array_2D)

1D Array:  [1 2 3 4 5 6 7]
2D Array:  [[1 2 3]
 [4 5 6]]


<h1>List VS Numpy</h1>

In [27]:
py_list = [1,2,3]
print("List Multiplication: ",py_list*2) 
py_array = np.array([1,2,3])
print("Array Multiplication: ",py_array*2) #Element Wise Multiplication

List Multiplication:  [1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]
Array Multiplication:  [ 2  4  6  8 10 12 14 16]


In [6]:
import time
import numpy as np
Start = time.time()
py_list = [i*2 for i in range(10000)]
print("List Opreation Time: ",time.time()-Start)

py_array = np.arange(0,10000)*2
print("Array Opreation Time: ",time.time()-Start)

/n List Opreation Time:  0.0010831356048583984
/n Array Opreation Time:  0.0021791458129882812


<h1>Creating Array From Scratch</h1>

In [10]:
import numpy as np

zeros_matrix = np.zeros((3,4))
print("Zeros Matrix: \n",zeros_matrix)

ones_matrix = np.ones((3,4))
print("Ones Matrix: \n",ones_matrix)

const_matrix = np.full((3,4),7)
print("Ones Matrix: \n",const_matrix)

random_matrix = np.random.random((3,4))
print("Random Matrix: \n",random_matrix)                             

sequence_matrix = np.arange()

Zeros Matrix: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Matrix: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Ones Matrix: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Matrix: 
 [[0.86215042 0.41576564 0.71966852 0.07385904]
 [0.41328791 0.197386   0.29297041 0.89970018]
 [0.01221895 0.23456419 0.44445406 0.26939979]]


<h1>Vector , Matrix , Tensor</h1>

In [3]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<h1>Array Properties</h1>

In [5]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
DType: int64


<h1>Array Reshaping</h1>

In [6]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
